import { User } from './types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'Alex Rivera',
    email: 'alex.rivera@example.com',
    jobTitle: 'Senior Software Engineer',
    department: 'Engineering',
    roles: ['Developer', 'Editor'],
    permissions: ['read:users', 'write:code', 'deploy:prod'],
    status: 'Active',
    createdAt: '2023-10-01',
  },
  {
    id: '2',
    name: 'Sarah Chen',
    email: 'sarah.chen@example.com',
    jobTitle: 'Product Manager',
    department: 'Product',
    roles: ['Manager', 'Editor'],
    permissions: ['read:all', 'edit:roadmap', 'manage:billing'],
    status: 'Active',
    createdAt: '2023-11-15',
  },
  {
    id: '3',
    name: 'Marcus Thorne',
    email: 'm.thorne@example.com',
    jobTitle: 'Security Specialist',
    department: 'Security',
    roles: ['Auditor', 'Admin'],
    permissions: ['read:logs', 'manage:iam', 'write:security-audit'],
    status: 'Active',
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    name: 'Elena Gilbert',
    email: 'elena.g@example.com',
    jobTitle: 'Junior Designer',
    department: 'Design',
    roles: ['Viewer'],
    permissions: ['read:assets', 'comment:designs'],
    status: 'Pending',
    createdAt: '2024-03-05',
  },
  {
    id: '5',
    name: 'Jordan Smith',
    email: 'j.smith@example.com',
    jobTitle: 'Marketing Lead',
    department: 'Marketing',
    roles: ['Editor'],
    permissions: ['read:campaigns', 'write:copy'],
    status: 'Inactive',
    createdAt: '2023-08-12',
  },
];